### PR TITLE
bugfix

### PR DESCRIPTION
**Pull request by yeyan**
fix Path import

### CODE REVIEW

**Comment by beeender** [comment]
@yeyan I think `Path` is not needed as import? Do you have problems to compile with it? What is the error message?

**Comment by yeyan** [comment]
@beeender 
Screen Shot 2019-04-02 at 3 56 09 pm

Apparently, Rust on OSX thinks a bit different.

**Comment by beeender** [comment]
Uh, right, I forgot that is used for mac only.
Could you please change the fix to 
```diff
 use std::path::{PathBuf};
 use std::env;

+#[cfg(target_os = "macos")]
+use std::path::Path;
+
```

since there would be a warning for Linux?

**Comment by beeender** [comment]
thanks!

**Comment by beeender** [comment]
@all-contributors please add @yeyan for code

**Pull request merged**
